# Generated by Django 5.2.9 on 2026-01-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_review"),
        ("events", "0003_event_created_at_event_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="accounts.currency",
            ),
        ),
    ]
