# Generated by Django 5.2.9 on 2026-01-12 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_offerthread_offermessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="accepted_thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_for_events",
                to="events.offerthread",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
