# Generated by Django 5.2.9 on 2026-01-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_event_accepted_professional"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_posted",
            field=models.BooleanField(default=True),
        ),
    ]
