# Generated by Django 5.2.9 on 2026-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_is_posted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcategory",
            options={
                "ordering": ["tree_path", "name"],
                "verbose_name_plural": "Event categories",
            },
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="tree_path",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=255
            ),
        ),
    ]
