# Generated by Django 5.2.9 on 2026-01-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_eventcategory_options_eventcategory_tree_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcategory",
            options={"ordering": ["name"], "verbose_name_plural": "Event categories"},
        ),
        migrations.RemoveField(
            model_name="eventcategory",
            name="tree_path",
        ),
    ]
