# Generated by Django 5.2.9 on 2026-01-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_alter_eventcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcategory",
            options={"ordering": ["path"], "verbose_name_plural": "Event categories"},
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="path",
            field=models.CharField(blank=True, db_index=True, max_length=600),
        ),
    ]
