# Generated by Django 5.2.9 on 2026-01-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_eventcategory_options_eventcategory_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
