# Generated by Django 5.2.9 on 2026-01-03 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accounts_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="professional_picture",
            field=models.ImageField(
                blank=True,
                default="professional_pictures/default_professional.png",
                null=True,
                upload_to="professional_pictures/",
            ),
        ),
        migrations.CreateModel(
            name="AccountPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="normal_pictures/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normal_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
