# Generated by Django 5.2.9 on 2026-01-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_audioacapellacover_videoacapellacover"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="nickname",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
