# Generated by Django 5.2.9 on 2026-01-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_accounts_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
