# Generated by Django 5.2.9 on 2026-01-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_accounts_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="about_me",
            field=models.TextField(blank=True, default=""),
        ),
    ]
