# Generated by Django 5.2.9 on 2026-01-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_accounts_about_me"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="accounts",
            name="communication_languages",
            field=models.ManyToManyField(
                blank=True, related_name="accounts_communication", to="accounts.language"
            ),
        ),
        migrations.AddField(
            model_name="accounts",
            name="event_languages",
            field=models.ManyToManyField(
                blank=True, related_name="accounts_events", to="accounts.language"
            ),
        ),
    ]
