# Generated by Django 5.2.9 on 2026-01-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_currency_accounts_cost_per_5_hours_and_more"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="accepted_event_categories",
            field=models.ManyToManyField(
                blank=True, related_name="accepted_by_users", to="events.eventcategory"
            ),
        ),
    ]
