# Generated by Django 5.2.9 on 2026-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_exchangerate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profession",
            options={"ordering": ["tree_path", "name"]},
        ),
        migrations.AddField(
            model_name="profession",
            name="tree_path",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=255
            ),
        ),
    ]
