# Generated by Django 5.2.9 on 2026-01-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_profession_options_profession_tree_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profession",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="profession",
            name="tree_path",
        ),
    ]
