# Generated by Django 5.2.9 on 2026-01-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_profession_options_remove_profession_tree_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profession",
            options={"ordering": ["path"]},
        ),
        migrations.AddField(
            model_name="profession",
            name="path",
            field=models.CharField(blank=True, db_index=True, max_length=600),
        ),
    ]
