# Generated by Django 5.2.9 on 2026-01-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_profession_options_profession_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="accounts",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="accounts",
            name="country",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
