# Generated by Django 5.2.9 on 2026-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_accounts_address_accounts_city_accounts_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=20,
                null=True,
            ),
        ),
    ]
