# Generated by Django 5.2.9 on 2026-01-22 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_accounts_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteProfessional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_professionals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "professional"],
                        name="accounts_fa_user_id_7cdaae_idx",
                    ),
                    models.Index(
                        fields=["professional"], name="accounts_fa_profess_31ba06_idx"
                    ),
                ],
                "unique_together": {("user", "professional")},
            },
        ),
    ]
