# Generated by Django 5.2.9 on 2026-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_favoriteprofessional"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="public_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Public-facing 8-digit user ID (non-guessable).",
                max_length=8,
                null=True,
                unique=True,
            ),
        ),
    ]
